### ISSUE TITLE
Connectathon Lab part 2 kubernetes deployment doesn't specify arch

### ISSUE THREAD

**Issue by siler23** [ibm-blockchain-wsc/ImmersionWorkshop#8]
This results in the application potentially getting deployed on x86 causing failure. 

Can fix this error after it happens with a kubectl patch i.e. `kubectl patch deployment marbles-$team-deploy --patch '{"spec":{"template":{"spec":{"nodeSelector":{"beta.kubernetes.io/arch":"s390x"}}}}}'` 

Alternatively, you could include this in the deployment itself by changing marbles-teamNN.yaml to 
```
apiVersion: v1
kind: Service
metadata:
  name: marbles-teamNN-svc
spec:
  selector:
    app: marbles-teamNN
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: marbles-teamNN-deploy
  labels:
    app: marbles-teamNN
spec:
  selector:
    matchLabels:
      app: marbles-teamNN
  replicas: 1
  template:
    metadata:
      labels:
        app: marbles-teamNN
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: s390x
      containers:
      - name: marbles-teamNN
        image: wsc-ibp-icp-cluster.icp:8500/lab-test/marbles-teamNN:1.0
        ports:
          - containerPort: 3001
        imagePullPolicy: Always
```
This needs to be done before lab.
